version: '3'

services:

  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    restart: always
    ports:
      - "28015:28015"
      - "29015:29015"
    volumes:
      - /data:/data
    command: rethinkdb --bind all --initial-password ${RETHINKDB_PW}

  nginx-rproxy-auth:
    image: cburki/nginx-rproxy-auth
    container_name: nginx-rproxy-auth
    restart: always
    environment: 
      - PROXY_AUTH_USERNAME=${PROXY_AUTH_USERNAME}
      - PROXY_AUTH_PASSWORD=${PROXY_AUTH_PASSWORD}
      - PROXY_SERVER_NAME=${PROXY_SERVER_NAME}
      - SERVICE_ADDRESS=${SERVICE_ADDRESS}
      - SERVICE_PORT=${SERVICE_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - rethinkdb

  bloxlink:
    image: ${IMAGE}
    container_name: bloxlink
    restart: always
    environment: 
      - RELEASE=MAIN
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/bloxlink
    depends_on:
      - rethinkdb

  bloxlink_pro:
    image: ${IMAGE}
    container_name: bloxlink_pro
    restart: always
    environment: 
      - RELEASE=PRO
    volumes:
      - /usr/src/bloxlink_pro
    depends_on:
      - rethinkdb

  bloxlink_canary:
    image: ${IMAGE}
    container_name: bloxlink_canary
    restart: always
    environment: 
      - RELEASE=CANARY
    volumes:
      - /usr/src/bloxlink_canary
    depends_on:
      - rethinkdb